package utility;


import java.util.List;

/**
 * <h1>Carbon Data Lookup Tables</h1>
 * <p>
 *     This interfaces stores the tree genera in Berlin both as complete list and categorised by their foliage
 *     habit in two more list
 * </p>
 *
 * @author Hannah Wollenweber
 * @version 1.0
 * @since 2024-02-20
 */
public interface TreesCategorized
{

    List<String> TOTAL_GENERA = List.of(
            "ABIES", "ACER", "AESCULUS", "AILANTHUS", "ALNUS", "AMELANCHIER", "BETULA", "BIOTA", "BUXUS", "CALOCEDRUS",
            "CARAGANA", "CARPINUS", "CARYA", "CASTANEA", "CATALPA", "CEDRUS", "CELTIS", "CEPHALOTAXUS", "CERCIDIPHYLLUM",
            "CERCIS", "CHAMAECYPARIS", "CHIONANTHUS", "CLADRASTIS", "CORNUS", "CORYLUS", "COTINUS", "CRATAEGUS",
            "CRYPTOMERIA", "CUPRESSOCYPARIS", "CUPRESSUS", "CYDONIA", "DAVIDIA", "ELAEAGNUS", "EUCOMMIA", "EUONYMUS",
            "FAGUS", "FRAXINUS", "GINKGO", "GLEDITSIA", "GYMNOCLADUS", "HAMAMELIS", "HIPPOPHAE", "ILEX", "JUGLANS",
            "JUNIPERUS", "KOELREUTERIA", "LABURNUM", "LARIX", "LIQUIDAMBAR", "LIRIODENDRON", "LONICERA", "MAGNOLIA",
            "MALUS", "MESPILUS", "METASEQUOIA", "MORUS", "NOTHOFAGUS", "NYSSA", "OSTRYA", "OXYDENDRUM", "PARROTIA",
            "PAULOWNIA", "PEROVSKIA", "PHELLODENDRON", "PICEA", "PINUS", "PLATANUS", "POPULUS", "PRUNUS", "PSEUDOLARIX",
            "PSEUDOTSUGA", "PTELEA", "PTEROCARYA", "PYRUS", "QUERCUS", "RHAMNUS", "RHUS", "ROBINIA", "SALIX", "SAMBUCUS",
            "SEQUOIA", "SEQUOIADENDRON", "SOPHORA", "SORBUS", "STYRAX", "SYRINGA", "TAMARIX", "TAXODIUM", "TAXUS",
            "TETRADIUM", "THUJA", "THUJOPSIS", "TILIA", "TOONA", "TROCHODENDRON", "TSUGA", "ULMUS", "WISTERIA", "ZELKOVA"
    );

    List<String> DECIDUOUS_GENERA = List.of(
            "ACER", "AESCULUS", "AILANTHUS", "ALNUS", "AMELANCHIER", "BETULA", "BUXUS", "CARAGANA",
            "CARPINUS", "CARYA", "CASTANEA", "CATALPA", "CELTIS", "CERCIDIPHYLLUM", "CERCIS", "CHIONANTHUS",
            "CLADRASTIS", "CORNUS", "CORYLUS", "COTINUS", "CRATAEGUS", "CYDONIA", "DAVIDA", "ELAEAGNUS",
            "EUCOMMIA", "EUONYMUS", "FAGUS", "FRAXINUS", "GINKGO", "GLEDITSIA", "GYMNOCLADUS", "HAMAMELIS",
            "HIPPOPHAE", "ILEX", "JUGLANS", "KOELREUTERIA", "LABURNUM", "LIQUIDAMBAR", "LIRIODENDRON",
            "LONICERA", "MAGNOLIA", "MALUS", "MESPILUS", "MORUS", "NOTHOFAGUS", "NYSSA", "OSTRYA",
            "OXYDENDRUM", "PARROTIA", "PAULOWNIA", "PEROVSKIA", "PHELLODENDRON", "PLATANUS", "POPULUS",
            "PRUNUS", "PTELEA", "PTEROCARYA", "PYRUS", "QUERCUS", "RHAMNUS", "RHUS", "ROBINIA", "SALIX",
            "SAMBUCUS", "SOPHORA", "SORBUS", "STYRAX", "SYRINGA", "TAMARIX", "TETRADIUM", "TILIA", "TOONA",
            "TROCHODENDRON", "ULMUS", "WISTERIA", "ZELKOVA"

    );

    List<String> CONIFEROUS_GENERA = List.of(
            "ABIES", "BIOTA", "CALOCEDRUS", "CEDRUS", "CEPHALOTAXUS","CHAMAECYPARIS", "CUPRESSOCYPARIS", "CUPRESSUS",
            "CRYPTOMERIA", "JUNIPERUS", "LARIX", "METASEQUOIA", "PICEA", "PINUS", "PSEUDOTSUGA", "PSEUDOLARIX", "SEQUOIA",
            "SEQUOIADENDRON", "TAXUS", "TAXODIUM", "THUJA", "THUJOPSIS", "TSUGA"
    );
}


