package utility;


import java.util.Arrays;
import java.util.List;


public interface TreeCategorized
{

    List<String> TOTAL_GENERA = List.of(
            "ABIES", "ACER", "AESCULUS", "AILANTHUS", "ALNUS", "AMELANCHIER", "BETULA", "BIOTA", "BUXUS", "CALOCEDRUS",
            "CARAGANA", "CARPINUS", "CARYA", "CASTANEA", "CATALPA", "CEDRUS", "CELTIS", "CEPHALOTAXUS", "CERCIDIPHYLLUM",
            "CERCIS", "CHAMAECYPARIS", "CHIONANTHUS", "CLADRASTIS", "CORNUS", "CORYLUS", "COTINUS", "CRATAEGUS",
            "CRYPTOMERIA", "CUPRESSOCYPARIS", "CUPRESSUS", "CYDONIA", "DAVIDIA", "ELAEAGNUS", "EUCOMMIA", "EUONYMUS",
            "FAGUS", "FRAXINUS", "GINKGO", "GLEDITSIA", "GYMNOCLADUS", "HAMAMELIS", "HIPPOPHAE", "ILEX", "JUGLANS",
            "JUNIPERUS", "KOELREUTERIA", "LABURNUM", "LARIX", "LIQUIDAMBAR", "LIRIODENDRON", "LONICERA", "MAGNOLIA",
            "MALUS", "MESPILUS", "METASEQUOIA", "MORUS", "NOTHOFAGUS", "NYSSA", "OSTRYA", "OXYDENDRUM", "PARROTIA",
            "PAULOWNIA", "PEROVSKIA", "PHELLODENDRON", "PICEA", "PINUS", "PLATANUS", "POPULUS", "PRUNUS", "PSEUDOLARIX",
            "PSEUDOTSUGA", "PTELEA", "PTEROCARYA", "PYRUS", "QUERCUS", "RHAMNUS", "RHUS", "ROBINIA", "SALIX", "SAMBUCUS",
            "SEQUOIA", "SEQUOIADENDRON", "SOPHORA", "SORBUS", "STYRAX", "SYRINGA", "TAMARIX", "TAXODIUM", "TAXUS",
            "TETRADIUM", "THUJA", "THUJOPSIS", "TILIA", "TOONA", "TROCHODENDRON", "TSUGA", "ULMUS", "WISTERIA", "ZELKOVA"
    );

    List<String> DECIDUOUS_GENERA = List.of(
            "ACER", "AESCULUS", "AILANTHUS", "ALNUS", "AMELANCHIER", "BETULA", "BIOTA", "BUXUS", "CALOCEDRUS", "CARAGANA",
            "CARPINUS", "CARYA", "CASTANEA", "CATALPA", "CELTIS", "CEPHALOTAXUS", "CERCIDIPHYLLUM", "CERCIS",
            "CHAMAECYPARIS", "CHIONANTHUS", "CLADRASTIS", "CORNUS", "CORYLUS", "COTINUS", "CRATAEGUS",
            "CYDONIA", "DAVIDA", "ELAEAGNUS", "EUCOMMIA", "EUONYMUS", "FAGUS", "FRAXINUS",
            "GINKGO", "GLEDITSIA", "GYMNOCLADUS", "HAMAMELIS", "HIPPOPHAE", "ILEX", "JUGLANS", "KOELREUTERIA",
            "LABURNUM", "LARIX", "LIQUIDAMBAR", "LIRIODENDRON", "LONICERA", "MAGNOLIA", "MALUS", "MESPILUS", "METASEQUOIA",
            "MORUS", "NOTHOFAGUS", "NYSSA", "OSTRYA", "OXYDENDRUM", "PARROTIA", "PAULOWNIA", "PEROVSKIA", "PHELLODENDRON",
            "PLATANUS", "POPULUS", "PRUNUS", "PSEUDOLARIX", "PTELEA", "PTEROCARYA", "PYRUS",
            "QUERCUS", "RHAMNUS", "RHUS", "ROBINIA", "SALIX", "SAMBUCUS", "SOPHORA", "SORBUS",
            "STYRAX", "SYRINGA", "TAMARIX", "TAXUS", "TETRADIUM", "THUJOPSIS", "TILIA", "TOONA",
            "TROCHODENDRON", "ULMUS", "WISTERIA", "ZELKOVA"

    );

    List<String> CONIFEROUS_GENERA = List.of(
            "ABIES", "CEDRUS", "CUPRESSOCYPARIS", "CUPRESSUS", "CRYPTOMERIA", "JUNIPERUS", "PICEA", "PINUS",
            "PSEUDOTSUGA", "SEQUOIA", "SEQUOIADENDRON", "TAXODIUM", "THUJA", "TSUGA"
    );
}


